### ISSUE TITLE
Auto and Service lights not working after yellow/red press to swap endstops.

### ISSUE THREAD

**Issue by bluemantwo** [jeffegg/EggysIVFW#7]
Starting from valve at 0 endstop, with Auto led flashing.  Press Yellow and Red buttons to swap endstops.   Valve moves to 24 endstop.  Auto light no longer is lit.  Also, using mode button, Service LED also does not light up.  Only Blue Set LED lights up.  Pressing Red/Yellow buttons to swap endstops back to original returns LEDs to normal function.  

Edit: having trouble reliably reproducing this.  I will try to better document, but has happened twice.

**Comment by jeffegg** [comment]
Hmm I cannot reproduce with the new FW with fix for the position LEDs I'll move back to the old FW and try again. I have noticed some oddness with the flashing auto light before, so I don't doubt that. Service mode should work. Can you try to reproduce and move to service mode and look at the nodejs dash valve interface (may want to do a refresh) I do report out the mode there. Want to verify we actually entered service mode.

**Comment by bluemantwo** [comment]
Will do, but after getting this 3 times, I have been unable to reproduce.  And it was not a functional issue.  Everything still worked, just the lights for Auto and Service would not light up.  Don't spend any time on this one.  If it comes up again, I will note what I did and try to reproduce.
